#!/usr/bin/env bash

# Check if poetry is installed
if ! type poetry &>/dev/null; then
    echo "Poetry is not installed. Please install it first."
    echo "See https://python-poetry.org/docs/#installation for more information."
    echo "curl -sSL https://install.python-poetry.org | python3 -"
    exit 1
# Check if poetry environment is exist, if not, install it
elif [[ ! -d .venv ]]; then
    export POETRY_VIRTUALENVS_PATH=./.venv
    poetry install
fi

export ANSIBLE_CONFIG=./ansible.cfg

poetry run ansible-playbook "$@"

exit $?
