---
vagrant:
  children:
    vagrant_control:
      hosts:
        controlplane01:
        controlplane02:
    vagrant_lb:
      hosts:
        loadbalancer:
    vagrant_nodes:
      hosts:
        node01:
        node02:

kube_control_plane:
  children:
    vagrant_control:

etcd:
  children:
    vagrant_control:

kube_load_balancer:
  children:
    vagrant_lb:

kube_nodes:
  children:
    vagrant_nodes:

k8s_cluster:
  children:
    kube_control_plane:
    kube_nodes:
